name: CML AMP Text-to-Image with Stable Diffusion
description: |
  Host Stable Diffusion in the form of UI and convert text to image in the CML platform.

author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2023-11-15"

environment_variables:
  PYTHONPATH:
    default: "/home/cdsw/.local/lib/python3.9/site-packages"
    description: "Leave this value as is. This is required by CML due to cml-addons module overriding user installed modules."
    required: true

runtimes:
  - editor: JupyterLab
    kernel: Python 3.9
    edition: Nvidia GPU

tasks:
  - type: run_session
    name: Install Dependencies
    script: download_requirements.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 4
    memory: 12
    
  - type: start_application
    name: Stable Diffusion Text to Image
    subdomain: CML-stable-diffusion
    script: start_app.py
    short_summary: Create and start CML Stable Diffusion application
    long_summary: Create and start CML Stable Diffusion application. Remember to enable unauthenticated app access for external access to the UI.
    cpu: 2
    memory: 8
    gpu: 1
    environment_variables:
      TASK_TYPE: START_APPLICATION
